### ISSUE TITLE
Content search UX questions and analysis

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/content_search#5]
* [x] What are our expectations around behavior of things like:
    * [x] phrase searching? #42 
    * [x] stemming?  sul-dlss/exhibits#979
    * [x] autocomplete? #14 
    * [x] hit highlighting improvements?
    * [x] collapsing hyphenated words across linebreaks? #10 
    * [x] adding additional content from the next page for phrase search? #10 
    * [x] handoff from the discovery to the viewer context? part of #33; see UniversalViewer/universalviewer#550
* [x] What are peer institutions doing? Sites to look at include:
    * Wellcome Library
    * North Carolina State University - Nubian Message: https://d.lib.ncsu.edu/collections/catalog?f%5Bclassification_facet%5D%5B%5D=The+Nubian+Message
    * National Library of Wales - journals: https://journals.library.wales
    * Johns Hopkins - Hamlet prompt book: https://iiifdemo.library.jhu.edu/demo/
    * IDA - http://universalviewer.io/uv.html?manifest=https://presley.dlcs-ida.org/iiif/idatest01/_roll_M-1011_127_cvs-423-453/manifest#?c=0&m=0&s=0&cv=2&xywh=-2%2C655%2C2150%2C2910
   * BL - http://universalviewer.io/uv.html?manifest=https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100026245410.0x000001/manifest.json#?c=0&m=0&s=0&cv=9&xywh=364%2C243%2C1037%2C1407
* [x] What do our stakeholders want?
    * Zoom behavior when paging through content search hits is disorienting sul-dlss/universalviewer#46

See also #10

**Comment by anarchivist** [comment]
**Yes** means the feature is supported.

| Feature | Wellcome | NCSU | NLW | JHU | IDA | BL | Other notes |
| ------- | ---------- | ---- | --- | --- | --- | --- | ----- |
| phrase searching | **Yes**. Does not use quotes to delimit phrases; quotes don't match phrase. Any multi-word term is treated as a phrase query. | **Yes.** Uses quotes to delimit phrases. | **Yes.** Quotes not necessary to delimit phrases. | **Yes**. Uses quotes to delimit phrases | **Yes.** Wellcome behavior. | **Yes.** Phrase queries behave unusually since they span word-level annos. | ... | 
| stemming | **Yes (root-out)** |  **Yes (root-out; variant-in)**  | **Yes (root-out)** | **Yes (root-out; variant-in)**  | **No** | **Yes (root-out; variant-in)** | root-out: `effect` matches `effective`, `effects`, etc; variant-in: `trained` matches `train`, etc. | 
| autocomplete | **Yes** |  **Yes**  | **No** | **No**  | **Yes** | **Yes** | ... | 
| hyphen/page break behavior |  |    |   |    |   |   | ... | 
| before/after |  |    |   |  **Yes**  |   |   | ... |

**Comment by ggeisler** [comment]
See #33 for UI suggestions that address some, though not all, of the questions raised in this ticket.
